#!/bin/bash

APIKEY=876be776d005785cbc6f885b7858811b

curl -H "Accept: application/json" "http://muslimsalat.com/tokyo.json?key=$APIKEY" 2>/dev/null > /tmp/fajr.time || (echo "Failed to fetch fajr time from server."; exit 1)
FTIME=$(sed 's/^.*"fajr":"\([0-9]\+\):\([0-9]\+\).*/\1:\2/g' /tmp/fajr.time) || exit 1
STIME=$(sed 's/^.*"shurooq":"\([0-9]\+\):\([0-9]\+\).*/\1:\2/g' /tmp/fajr.time) || exit 1

SMINUTE=$(echo $STIME | cut -b 3-5)
SHOUR=$(echo $STIME | cut -b 1)

if [ $(($SMINUTE+15)) -ge 60 ]; then
	SMINUTE=$((SMINUTE+15-60))
	SHOUR=$((SHOUR+1))
else
	SMINUTE=$((SMINUTE+15))		
fi

[ $SMINUTE -lt 10 ] && SMINUTE=0$SMINUTE

STIME=$SHOUR:$SMINUTE

FMINUTE=$(echo $FTIME | cut -b 3-5)
FHOUR=$(echo $FTIME | cut -b 1)
FHOUR=$((FHOUR-1))

FTIME=$FHOUR:$FMINUTE

echo fajr = $FTIME
echo shurooq = $STIME

# schedule lamp switch
at $FTIME -f /usr/lib/cgi-bin/mlampbon.cgi &&
at $STIME -f /usr/lib/cgi-bin/mlampboff.cgi
